path:
  ckpt_path: "./output/ckpt/LibriTTS_meta_learner"
  log_path: "./output/log/LibriTTS_meta_learner"
  result_path: "./output/result/LibriTTS_meta_learner"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
  lr_disc: 0.00002
  alpha: 10
# step:
#   meta_learning_warmup: 5
#   total_step: 7
#   log_step: 3
#   synth_step: 3
#   val_step: 3
#   save_step: 4
step:
  meta_learning_warmup: 60000
  total_step: 100000
  log_step: 50
  synth_step: 500
  val_step: 500
  save_step: 10000